site_title = "MyArxiv-for Reinfocement Learning"
limit_days = 7
cache_url = "https://w863071864.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.AI"
title = "Computation and Language"

[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 150
category = "cs.GT"
title = "Computer Science and Game Theory"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.NE"
title = "Information Retrieval"

[[sources]]
limit = 150
category = "stat.ML"
title = "Machine Learning"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
